# Generated by Django 2.0.2 on 2020-05-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_cnae',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='contador_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='diretor_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='gerente_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
