# Generated by Django 2.0.2 on 2020-05-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidowebitem',
            name='participante',
        ),
    ]
