# Generated by Django 2.0.2 on 2019-03-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_auto_20190320_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidowebitem',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienteItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
