# Generated by Django 2.0.2 on 2020-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('materiais', '0004_produto_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='empresa',
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
