# Generated by Django 2.0.2 on 2020-05-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_participantetipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipanteTipo',
        ),
    ]
