# Generated by Django 2.0.2 on 2020-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_auto_20200519_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
