# Generated by Django 2.0.2 on 2020-05-19 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0007_auto_20200519_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 5, 19, 13, 47, 53, 958644, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
