# Generated by Django 2.0.2 on 2020-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0008_auto_20200519_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF'),
        ),
    ]
