# Generated by Django 2.0.2 on 2020-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_auto_20200519_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código'),
        ),
    ]
