# Generated by Django 2.0.2 on 2020-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0013_auto_20200519_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='bairro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
    ]
