# Generated by Django 2.0.2 on 2020-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0015_auto_20200519_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
    ]
