# Generated by Django 2.0.2 on 2020-05-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_auto_20200515_1208'),
        ('empresas', '0002_auto_20200519_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPrecoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=16)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.Produto')),
                ('tabelapreco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.TabelaPreco')),
            ],
        ),
    ]
